### ISSUE TITLE
Can An AbstractFileBasedApplication handles many FileBasedActivities?

### ISSUE THREAD

**Issue by meeterp** [wrandelshofer/jhotdraw8#5]
Do you plan to support An AbstractFileBasedApplication handles many FileBasedActivities?
For example, AbstractFileBasedApplication has only one common MenuBar, one Toolbar, one primaryStage, but has many FileBasedActivities, All FileBasedActivities have common MenuBar, Toolbar and primaryStage

**Comment by morethank-projects** [comment]
Can one stage have many activities? such as one stage show many activities in a TabPane, user can switch to different activity when needed. all activities have the same MenuBar and Toolbar

**Comment by wrandelshofer** [comment]
> Do you plan to support An AbstractFileBasedApplication handles many FileBasedActivities? For example, AbstractFileBasedApplication has only one common MenuBar, one Toolbar, one primaryStage, but has many FileBasedActivities, All FileBasedActivities have common MenuBar, Toolbar and primaryStage

This is already supported. Try this out:

1. In module org.jhotdraw8.teddy run TeddyApplication.
2. This will open one Stage with one TeddyActivity.
3. Select the menu File/New or File/Open... to open addtional stages. Each Stage will have a new instance of TeddyActivity.

**Comment by wrandelshofer** [comment]
> Can one stage have many activities? For Example, one stage show many activities in a TabPane, user can switch to different activity when needed. all activities have the same MenuBar and Toolbar

This is currently not supported. This would require an AbstractTabbedApplication. You can create such a class by yourself in your own project.

**Comment by meeterp** [comment]
How to implement a figure which support child figures, and child figures can be moved separately.

**Comment by wrandelshofer** [comment]
| How to implement a figure which support child figures, and child figures can be moved separately.
| A PageFigure can have a child PageLabelFigure, but the PageLabelFigure cannot be moved separately, only be 
| moved by PageFigure's moving together.

This is supported, the UI provides two features for this. 

**Feature 1: "Select Children"**

You can move the PageLabelFigure by performing the following steps:
1. Select the PageFigure in the drawing view
2. Choose the menu item "Edit > Select Children"
3. Now, the drawing view shows handles for the PageLabelFigure
4. You can now move the PageLabelFigure. 

This feature is quite finicky. You have to be careful to not select any other figure. If it happens, you have to perform the steps again.

This feature also works for "GroupFigure". Allowing to move children of a group, without having to ungroup them.

When I get to rework the feature, the finished UI will allow to select any figure in the Hierarchy Inspector as the "active parent". All tools and editing function will only act on descendants of the "active parent". 

There is a property with that name in the DrawingView interface. But it does not have much of an effect yet.

**Feature 2: "Hierarchy Inspector"**

You can move the PageLabelFigure by performing the following steps:
1. Select the PageLabelFigure in the Hierarchy Inspector
2. Now, the drawing view shows handles for the PageLabelFigure
3. You can now move the PageLabelFigure.
