### ISSUE TITLE
How to use AbstractElbowLineConnectionWithMarkersFigure

### ISSUE THREAD

**Issue by meeterp** [wrandelshofer/jhotdraw8#7]
Can you give an example about how to use AbstractElbowLineConnectionWithMarkersFigure?
AbstractElbowLineConnectionWithMarkersFigure contains Polyline, startMarker and endMarker, so I hope the example can draw a polyline with many points which connects two figures, Thanks a lot.

**Comment by meeterp** [comment]
Can you explain why can AbstractElbowLineConnectionWithMarkersFigure move along with it's START_TARGET or END_TARGET?

**Comment by wrandelshofer** [comment]
I have now committed an example figure that implements AbstractElbowLineConnectionWithMarkersFigure into the main branch.

The name of the class is ElbowLineConectionWithMarkesFigure:
https://github.com/wrandelshofer/jhotdraw8/blob/72194870f7e37b9b086cc6abe2f42f01b44363e7/org.jhotdraw8.draw/src/main/java/org.jhotdraw8.draw/org/jhotdraw8/draw/figure/ElbowConnectionWithMarkersFigure.java

You can run the Grapher Demo application to try it out. The figure is available in the toolbar.

**Comment by wrandelshofer** [comment]
> Can you explain why can AbstractElbowLineConnectionWithMarkersFigure move along with it's START_TARGET or END_TARGET?

You can look at the first couple of lines in the `layout(RenderContext ctx)` method of AbstractElbowLineConnectionWithMarkersFigure.

The algorithm is as follows:

1. Get the stored start and end points by calling getNonNull(START) and getNonNull(END).
2. If we have a START_TARGET and a START_CONNECTOR, use them to compute an initial start point by calling startConnector.getPointAndDerivativeInWorld().  The initial start position is somewhere inside the shape of the figure.
3. Do the same for END_TARGET and END_CONNECTOR;
4. Compute the intersection point at the border of the start figure by calling startConnector.chopStart() with the start figure, and the intial start and end points.
5. Compute the intersection point at the border of the end figure by calling endConnector.chopStart() with the end figure and the intial start and end points (given in reverse order).
6. Store the points that we have found by calling set(START, ...) and set(END, ...)

The code does some additional stuff with the derivative of the intersection points. The derivatives are used for layouting the elbow line.

As you can see, the computation of the location of the start/end points is performed by calling methods on `Connector` objects.
The `Connector` objects are created by the target figures. See `ConnectableFigure.findConnector()` methods.

https://github.com/wrandelshofer/jhotdraw8/blob/ad5bf67c859e04b8cacc14278b03e85caa50ae58/org.jhotdraw8.draw/src/main/java/org.jhotdraw8.draw/org/jhotdraw8/draw/figure/AbstractElbowLineConnectionWithMarkersFigure.java#L238-L276

**Comment by meeterp** [comment]
Thanks a lot.
Why is the layout(RenderContext ctx) method of AbstractElbowLineConnectionWithMarkersFigure? Is the result of the doAddedToDrawing(final Drawing drawing) method of AbstractLineConnectionFigure adding AbstractLineConnectionFigure to layoutObservers of START_TARGET or END_TARGET figure?

**Comment by wrandelshofer** [comment]
Yes. A Figure, that observes the layout of another Figure, has to add itself as a layoutObserver on the other figure.

The layout algorithm in SimpleDrawingModel uses layoutObservers to determine in which sequence the figures must be laid out. SimpleDrawingModel builds a graph, and then sorts it topologically. 

https://github.com/wrandelshofer/jhotdraw8/blob/ad5bf67c859e04b8cacc14278b03e85caa50ae58/org.jhotdraw8.draw/src/main/java/org.jhotdraw8.draw/org/jhotdraw8/draw/model/SimpleDrawingModel.java#L417-L423
